-- Eliminar la tabla de hechos primero, luego las dimensiones
DROP TABLE IF EXISTS FACT_VUELO;
DROP TABLE IF EXISTS DIM_AIRLINE;
DROP TABLE IF EXISTS DIM_AIRPORT;
DROP TABLE IF EXISTS DIM_DATE;
DROP TABLE IF EXISTS DIM_PASSENGER;